### ISSUE TITLE
Unable to submit new article form

### ISSUE THREAD

**Issue by rbertram90** [Smith0r/bulletin#87]
The submit button on creating a new article is not doing anything when clicked.

Not getting any javascript errors, tried in Chrome & FF. 😕

**Comment by Smith0r** [comment]
@rbertram90 I came across this issue too and was equally as confused! I discovered it was to do with a required field i'd left in the xml form which tinymce just doesn't like!

It's fixed in [this commit](https://github.com/Smith0r/bulletin/commit/b8ed27d8d06845a67f631492a2bd3014cd677b26), and will be in the next version (Hopefully on Friday!).

Let me know if that fixes it for you. Cheers!
